spring:
  profiles:
    active: heroku



  ################################################
  application:
    name: Shop Demo
  mail:
    host: ${MAIL_HOST} #smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT} #587
    properties.mail.smtp.starttls.enable: true
################################################
server:
  port: 8080
  use-forward-headers: true

app:
  jwtSecret: E286115114967D4F9A82BF2C292E4
  jwtExpirationInMs: 604800000
